name 'conzar-pidservice'
version '0.1.1'
author 'Michael Speth'
license 'GPLv3'
source 'https://github.com/Conzar/pidservice'
summary 'Installs and manages the PIDService'
description 'Persistent Identifier Service (PID Service) enables resolution of persistent identifiers.'
project_page 'https://www.seegrid.csiro.au/wiki/Siss/PIDService'
dependency 'puppetlabs/postgresql', '>=3.3.3'
dependency 'puppetlabs/apache', '>=1.0.1'
dependency 'conzar/check_run', '>=0.2.0'
dependency 'conzar/tomcat6', '>=0.1.0'
